### ISSUE TITLE
doesn't support texture coordinates with just two entries

### ISSUE THREAD

**Issue by WurmD** [Thekla/thekla_atlas#29] opened 2020-02-27 15:35 UTC
The below works, add it in to support obj files where the `vt` lines only contain 2 numbers
(the `n` computation, and use)

		mesh->vertex_array = new Obj_Vertex[mesh->vertex_count];
		for (int s = 0, nv = 0; s < shapes.size(); s++) {
			const int shape_vertex_count = (int)shapes[s].mesh.positions.size() / 3;

			int n;
			if (shapes[s].mesh.positions.size() == shapes[s].mesh.texcoords.size())
				n = 3;
			else if (shapes[s].mesh.positions.size() / 3 == shapes[s].mesh.texcoords.size() / 2)
				n = 2;

			for (int v = 0; v < shape_vertex_count; v++) {
				mesh->vertex_array[nv + v].position[0] = shapes[s].mesh.positions[v * 3 + 0];
				mesh->vertex_array[nv + v].position[1] = shapes[s].mesh.positions[v * 3 + 1];
				mesh->vertex_array[nv + v].position[2] = shapes[s].mesh.positions[v * 3 + 2];
				mesh->vertex_array[nv + v].normal[0] = shapes[s].mesh.normals[v * 3 + 0];
				mesh->vertex_array[nv + v].normal[1] = shapes[s].mesh.normals[v * 3 + 1];
				mesh->vertex_array[nv + v].normal[2] = shapes[s].mesh.normals[v * 3 + 2];
				mesh->vertex_array[nv + v].uv[0] = shapes[s].mesh.texcoords[v * n + 0];      // The input UVs are provided as a hint to the chart generator.
				mesh->vertex_array[nv + v].uv[1] = shapes[s].mesh.texcoords[v * n + 1];

**Comment by castano** [comment] 2020-05-26 05:45
Duplicate of issue #32.

**Closed by castano** 2020-05-26 05:45 UTC
